#!/usr/bin/env node

const puppeteer = require('puppeteer');
const fs = require('fs');
const { execSync } = require('child_process');
const path = require('path');
const { program } = require('commander');

program
  .argument('<filePath>', 'path to the SVG file')
  .option('-o, --output <output>', 'output file name')
  .option('-d, --delay <delay>', 'delay between frames in milliseconds', '100')
  .option('-c, --count <count>', 'number of frames to capture', '10')
  .parse(process.argv);

const filePath = program.args[0];
const delay = parseInt(program.opts().delay, 10);
const frames = parseInt(program.opts().count, 10);

if (!filePath) {
  console.error('Please provide the path to the SVG file as an argument.');
  process.exit(1);
}

const absoluteFilePath = path.resolve(filePath);
const defaultOutputFileName = path.basename(filePath, path.extname(filePath)) + '.apng';
const outputFileName = program.opts().output || defaultOutputFileName;

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto(`file://${absoluteFilePath}`);

  for (let i = 0; i < frames; i++) {
    // Try to capture the frame every `delay` milliseconds regardless of how long it takes to render
    let nextFrameDelay = new Promise(resolve => setTimeout(resolve, delay));
    const framePath = `frame-${i}.png`;
    await page.screenshot({ path: framePath });
    await nextFrameDelay;
  }

  execSync(`apngasm --force -o ${outputFileName} -d ${delay} frame-*.png`);
  console.log(`APNG file created: ${outputFileName}`);

  // Remove frame-*.png files
  for (let i = 0; i < frames; i++) {
    const framePath = `frame-${i}.png`;
    fs.unlinkSync(framePath);
  }

  await browser.close();
})();